name: ollo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  fl_chart: ^0.69.0
  flutter_svg: ^2.2.3
  path_provider: ^2.1.5
  uuid: ^4.3.3
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.9.1
  home_widget: ^0.8.1
  speech_to_text: ^7.3.0
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: any
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"
  min_sdk_android: 21

dependency_overrides:
  vector_math: ^2.1.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/wallets/
    - assets/wallets/bri.svg
    - assets/images/
